# You are given a JSON file containing performance data for several Facebook ad campaigns.

# Each campaign object in the JSON array includes the following keys:

# - campaign_id: A unique identifier for the campaign.
# - budget: The total amount spent on the campaign.
# - impressions: The number of times the ad was displayed.
# - clicks: The number of clicks the ad received.
# - conversions: The number of conversions generated by the campaign.

# Your task is to compute the Cost Per Click (CPC) for each campaign using the formula:

# CPC = budget / clicks  
# Then output the top 3 most cost-effective campaigns by displaying the campaign_id and the computed CPC.

# The campaigns should be sorted in ascending order by CPC (i.e. lower CPC is more cost-effective).

# Sample Data (JSON):

# [  {    "campaign_id": "CAMP001",    "budget": 1000,    "impressions": 50000,    "clicks": 250,    "conversions": 10  },  {    "campaign_id": "CAMP002",    "budget": 800,    "impressions": 40000,    "clicks": 200,    "conversions": 8  },  {    "campaign_id": "CAMP003",    "budget": 1200,    "impressions": 60000,    "clicks": 300,    "conversions": 12  }]


import json

filepath = "/Users/krahman/Documents/Cisco/Documents/Personal/Interview Prep/Automation/Meta Question/performance_data.json"
campaign = []
with open(filepath, mode='r') as file:
    content = json.load(file)
    print(content)
    for row in content:
    	campaign_id = row['campaign_id']
    	print(campaign_id)
    	budget = int(row['budget'])
    	impression = int(row['impressions'])
    	clicks = int(row['clicks'])
    	conversions = int(row['conversions'])
    	cpc = budget / clicks
    	campaign.append((campaign_id, cpc))
print(campaign)

campaign.sort(key=lambda x:x[1], reverse=True)

print(campaign)

for camp in campaign[:2]:
	print(f"Campaign ID:", camp[0], f"CPC Score:", camp[1])
	print(f"Campaign ID: {camp[0]} - CPC Score: {(camp[1])}")


